#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
  /assets \
  /config/{nginx/site-confs,log/nginx} \
  /run \
  /var/lib/nginx/tmp/client_body \
  /var/tmp/nginx

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] && \
  cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ ! -f /config/nginx/site-confs/default ]] && \
  cp /defaults/default /config/nginx/site-confs/default
  
# Ownership
chown -R abc:abc /assets